server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elastic_search?useSSL=false
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: 192.168.0.118
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo